### ISSUE TITLE
24V support

### ISSUE THREAD

**Issue by dlsnet** [srg74/WLED-wemos-shield#100]
Hi, Can this board be used for 24V strips (assuming that I replace  DC to DC converter with something supporting 24 to 5 V conversion)?

Thank you.

**Comment by srg74** [comment]
Actually buck converter on board should work up to 36V, but to be honest, I never tested with 24V addressable strips.

**Comment by dlsnet** [comment]
So, theoretically, you don't see why it wouldn't work?

**Comment by srg74** [comment]
> So, theoretically, you don't see why it wouldn't work?

Yes, I don't see why shouldn't.
