### ISSUE TITLE
Request: debug build with Hue support

### ISSUE THREAD

**Issue by ceeeekay** [srg74/WLED-wemos-shield#101]
Hi there,

Re. https://github.com/Aircoookie/WLED/issues/3083 could I please request a debug build of v0.14.0-b2 with Hue support compiled in?

I'm trying to get some logging output for a crash/reboot issue with Hue sync enabled, but I don't have a current build env, and I have my first child arriving this week so it's not something I can spare much time for.

If you could help me out that would be great thanks :)

**Comment by srg74** [comment]
Done. https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/%40Aircoookie/v0.14.0-b2/Debug_builds

**Comment by ceeeekay** [comment]
Awesome - thank you so much!
