### ISSUE TITLE
Request: panelized version

### ISSUE THREAD

**Issue by DasKatzchen** [srg74/WLED-wemos-shield#102]
The board is ~45mm in the shortest dimension, and the $5 boards from PCBWay can be up to 100mm square. Would it be possible to make a panelized version with two boards per? Could probably fit one or two of the add-on boards too, it's free real estate. 
https://github.com/ThisIsNotRocketScience/GerberTools is a really good tool for this.

**Comment by srg74** [comment]
Problem with the panel at PCBway they will not pass inspection as single board. So price would be greater. At least I have tried once.

**Comment by DasKatzchen** [comment]
Huh, other fab houses I've used don't care. I guess it's good to know ahead of time that PCBWay will fail a board for that.
