### ISSUE TITLE
Schematic Question

### ISSUE THREAD

**Issue by lathemaster** [srg74/WLED-wemos-shield#103]
I was looking at the V3 schematic as a learning exercise and how that relates to the pcb.
Was not familiar with these symbols?
![image](https://user-images.githubusercontent.com/895986/218165096-36917cb6-1b4a-440c-8fdc-70a2023d758f.png)
![image](https://user-images.githubusercontent.com/895986/218165415-f7ba16eb-459c-479b-93ab-e7ef8939a7b5.png)

Thanks in advance
Mike

**Comment by srg74** [comment]
Solder jumper pads

**Comment by lathemaster** [comment]
Thanks
