### ISSUE TITLE
WS2815 12V strip

### ISSUE THREAD

**Issue by malinin24** [srg74/WLED-wemos-shield#104]
How it work with 12V led strip like WS2815?
WS2815 need 12V logic level on Din.

**Comment by srg74** [comment]
Logic levels for outputs is TTL (5V). Power for 12V strip is 12V but logic is still 5V.

**Comment by malinin24** [comment]
I bought a 2815 LED strip on aliexpress. It does not work from 5 volts of logic. Judging by the wiring diagram of the LEDs, the VCC output is connected directly to 12 volts. When the 12 volt logic level is applied, the LEDs will light up. While I don’t have a normal 5 volt to 12 volt logic level converter, I can’t fully check the tape.

**Comment by srg74** [comment]
On shield level shifter providing all necessary signal levels. You feeding to a shield 12 VDC and you have to move jumper to 12v position. LEDs strip WS2815 power wires to power out from shield and data signal to strip markings DI. Also on strip BI wire must be connected with GND. This setup must work without any problems.
