### ISSUE TITLE
3568 Fuse Holder on LCSC

### ISSUE THREAD

**Issue by guilhermebera** [srg74/WLED-wemos-shield#109]
In BOM 2.1 its like "36-3568-ND" what is Digikey code, on LCSC I find C3205378 and C3206956 that it's just a a different color.

**Comment by srg74** [comment]
Both parts is not available for purchase only for "Get a Quote".

**Comment by cybergurke** [comment]
I had the same problem. I ordered these: https://de.aliexpress.com/item/4000583874791.html
They fit well.
