### ISSUE TITLE
esp32s2 0.13.3 works but 0.14.0b2 does not 

### ISSUE THREAD

**Issue by Apprisco** [srg74/WLED-wemos-shield#110]
0.13.3 showed working on install.wled.me after 0x1000 0x8000 and 0x10000 flash
0.14.0-b2 does not

**Comment by Apprisco** [comment]
File obtained from @Aircookie's firmware folder in this project, will try Blazenrock's next, saola esp32s2

**Comment by srg74** [comment]
All binaries build from @Aircoookie repo is nightly builds, please report to WLED Discord or to a original [repo](https://github.com/Aircoookie/WLED) about bugs.
