### ISSUE TITLE
error with WLED_0.14.0-b3_esp8266_dallas_mod.bin

### ISSUE THREAD

**Issue by Francesco-Rugg** [srg74/WLED-wemos-shield#111]
I'm trying to flash **0.14.0-b3_esp8266_dallas_mod.bin** on my wemos D1, but every time I got this error

![1687342638576](https://github.com/srg74/WLED-wemos-shield/assets/62062196/46a1fc00-07b7-4d62-99a8-c35830898336)
 
but If I use the bin file **0.13.3_esp8266_display_dallas.bin** everythings works as expected

**Comment by srg74** [comment]
Backup you presets and settings, erase your board and upload new bin. 0.14 can’t go on top of 0.13

**Comment by Francesco-Rugg** [comment]
Ok, thank you I will try and let you know

**Comment by Francesco-Rugg** [comment]
> Backup you presets and settings, erase your board and upload new bin. 0.14 can’t go on top of 0.13

OK, so I got it. 
The problem with 0.14 version is the AP mode that cause this issue.
First things to do with 0.14 version is to connect the wled to a network and the error will not appear!

thanks @srg74
