### ISSUE TITLE
DC/DC converter - backwards?

### ISSUE THREAD

**Issue by numindast** [srg74/WLED-wemos-shield#112]
Hi there :) PCBway asked me about an order I placed and I'm confused.

The DC/DC converter appears to be inserted this way, with PIN 1 towards the screw terminals:
![image](https://github.com/srg74/WLED-wemos-shield/assets/89759032/1cfe8500-8dde-4c2a-b6eb-dfde6c468173)

However in your images on Tindie and Github, PIN 1 is away from the screw terminals:
![image](https://github.com/srg74/WLED-wemos-shield/assets/89759032/c4d252d3-0db7-4534-8cb7-2bdd868483b5)

I'm having PCBWay bag the buck converter for me to solder later, so I can check which thru-hole is the 5v bus and which is Vin. But would love to understand the issue. Thanks so much for your awesome design. (I believe in the future I'll just order your more updated SMD version off Tindie since it's a little more cost effective)

Update: just realized the part in your photos is not the same part, perhaps I'm overthinking this.

**Comment by srg74** [comment]
By default you have to use 500mA buck converter on DIY board. On SMD board 1A buck converter is placed and they have different pinout.

**Comment by srg74** [comment]
On pic with green pcb buck placement is correct.

**Comment by numindast** [comment]
Ahh I understand! Thanks again! Your community support is much appreciated, I'm sure by many.
