### ISSUE TITLE
IR receiver not working on WLED_0.14.0-b5_sp511e_2m

### ISSUE THREAD

**Issue by xbmcnut** [srg74/WLED-wemos-shield#114]
I've just yesterday used [this guide](https://github.com/scottrbailey/WLED-Utils/blob/gh-pages/sp511e_wled.md) to install WLED on two 511e and it works awesome but I could not get the included remote to work with [WLED_0.14.0-b5_sp511e_2m.bin](https://github.com/srg74/WLED-wemos-shield/blob/master/resources/Firmware/%40Aircoookie/Latest/WLED_0.14.0-b5_sp511e_2m.bin).

I set the remote GPIO to pin 5 as suggested and uploaded the appropriate remote JSON file. I had two remotes so I could check with both. Neither worked.

After an hour or so, I rolled back to https://github.com/scottrbailey/WLED-Utils/raw/gh-pages/firmware/soundReactive_0.13.0-b3_sp511e.bin and both remotes started working instantly without having to change any settings.

Let me know if you need me to supply any files but at this stage it's just a heads-up for anyone trying to get the remote working with this latest beta.

**Comment by srg74** [comment]
Fixed. Should work as intended.
