### ISSUE TITLE
Alexa Support in WLED_0.14.0_sp511e_2m.bin

### ISSUE THREAD

**Issue by detafun** [srg74/WLED-wemos-shield#115]
Hallo,
bitte den Alexa Support mit einbauen. Wäre echt klasse.
Ich habe den sp511e

Danke

Hello,
Please include Alexa support. Would be really great.
I have the sp511e

Thanks

cu Deta

**Comment by srg74** [comment]
Hallo,
Bitte laden Sie die neueste Binärdatei herunter

**Comment by detafun** [comment]
> Hallo, Bitte laden Sie die neueste Binärdatei herunter

Ich hab alle probiert, immer kein Alexa Support.

**Comment by detafun** [comment]
Ha danke gerade gesehen, das ein Update gemacht hast. Super.
Wie sieht es eigentlich aus mir dem Sound Efekten?

**Comment by srg74** [comment]
Ich verwende SP511E nicht.

**Comment by detafun** [comment]
ok, der hat ein eingebautes Mic, früher gab es mal WLED mit soundReactive. Nur noch in einer alten Version. Und die hat Bugs ALexa zwar da , wird aber nicht gefunden, FB funktioniert nicht richtig....

**Comment by detafun** [comment]
Ich komme so langsam dahinter, Aber das Problem ist, das noch was nicht aktiviert ist.
This firmware build does not include simplified UI support

`Server description: 
WLED-SoundReactive

Sync button toggles both send and receive: 
This firmware build does not include simplified UI support.
The following UI customization settings are unique both to the WLED device and this browser.
You will need to set them again if using a different browser, device or WLED IP address.
Refresh the main UI to apply changes.`

**Comment by srg74** [comment]
All of the features can be set over settings. Please visit WLED Discord channel for further discussions. I only providing complimentary bin files for various configurations.

**Comment by detafun** [comment]
Danke
