### ISSUE TITLE
Multiple antivirus scanners have flagged the files `Windows.zip` and `ESP-Flasher.exe` as potentially malicious. This raises concerns about the safety and integrity of these files.

### ISSUE THREAD

**Issue by brammittendorff** [srg74/WLED-wemos-shield#116]
### Affected Files
1. `Windows.zip`
   - VirusTotal link: [Windows.zip analysis](https://www.virustotal.com/gui/file/406af8122dafa645503730bf2737e0bff72a00721d83657122b96981108af34d)
2. `ESP-Flasher.exe`
   - VirusTotal link: [ESP-Flasher.exe analysis](https://www.virustotal.com/gui/file/4cb6874972cd54a8644d2e5156be408230232b4733f54407d56922ab4d31a381)

### Malware Scan Results
- `Windows.zip`: Detected as malicious by 1 out of 73 antivirus scanners.
- `ESP-Flasher.exe`: Detected as malicious by 5 security vendors. Notably, it was flagged by Bkav Pro, Cynet, DeepInstinct, SecureAge, and Skyhigh (SWG).

### Concerns
Given these detections, there is a concern that these files may contain harmful components that could compromise user security. Users of this repository should be made aware of these potential risks.

### Request
We kindly request an investigation into these files to verify their safety. If they are indeed compromised, we suggest removing or replacing them to ensure the security of all users.

### Additional Information
- File Sizes:
  - `Windows.zip`:  15.2 MB 
  - `ESP-Flasher.exe`: 15.46 MB

Thank you for your attention to this matter. Ensuring the security and integrity of software is paramount, and your assistance is greatly appreciated.

**Comment by srg74** [comment]
This software was used by multiple users and never has been reported as a virus. Most likely it's a false alarm.

**Comment by brammittendorff** [comment]
> This software was used by multiple users and never has been reported as a virus. Most likely it's a false alarm.

Alright, just a heads up then.
