### ISSUE TITLE
Error in Digikey part list

### ISSUE THREAD

**Issue by w00000dy** [srg74/WLED-wemos-shield#12]
Hey,
something is wrong with [Digikey part list](https://github.com/srg74/WLED-wemos-shield/blob/master/resources/WLED_Wemos_shield_Digikey.csv). The quantity doeas not match with the [BOM](https://github.com/srg74/WLED-wemos-shield/blob/master/resources/BOM.pdf). I don't know if there are any more errors.

**Comment by srg74** [comment]
Fixed.

**Comment by w00000dy** [comment]
Thank you very much!
