### ISSUE TITLE
Documentation Bug - broken link to bootloader

### ISSUE THREAD

**Issue by alastaira** [srg74/WLED-wemos-shield#121]
Hi!

On the documentation page at https://github.com/srg74/WLED-wemos-shield/wiki/Firmware there is a hyperlink to download the bootloader from https://github.com/espressif/arduino-esp32/tree/master/tools/sdk/esp32/bin . This leads to a 404. 

I believe the latest version that this should point to is instead:
https://github.com/espressif/arduino-esp32/tree/2.0.5/tools/sdk/esp32/bin

?
Thanks!

**Comment by srg74** [comment]
Thank you for your help! Link fixed.
