### ISSUE TITLE
OTA update for sp511e fails

### ISSUE THREAD

**Issue by siretart** [srg74/WLED-wemos-shield#122]
when trying to OTA update (manual update / upload method), I'm seeing the error message:

![image](https://github.com/user-attachments/assets/7c96b1d5-eda8-46c7-952f-fa3114230c70)

**Comment by siretart** [comment]
possibly related to #91 ?

**Comment by srg74** [comment]
OTA will not work due to memory size. You can update over serial.

**Comment by siretart** [comment]
any OTA capable builds available with reduced functionality you could point to?

**Comment by srg74** [comment]
None of the builds will fit OTA.

**Comment by siretart** [comment]
okay, thanks for confirming
