### ISSUE TITLE
Relay does not switch off

### ISSUE THREAD

**Issue by spad** [srg74/WLED-wemos-shield#123]
My setup:
- universal shield with relay
- Wemos ESP32
- WLED 1.4.4

When I power the shield, the relay is off. Pushing the button, the relay switch to on but never switch off when the button is pressed again , nor when switching the "Power" menu in the UI. The LEDs, btw, are working as expected.

Using the board without shield, IO019 has level 0 and 3.2V when pressing the Power in the UI..
Wen mounted on the shield these levels are 0V and 2.5V

**Comment by srg74** [comment]
Check in the relay settings first

**Comment by spad** [comment]
This is my setting for the relay option

![Immagine 2024-12-05 143511](https://github.com/user-attachments/assets/0c953400-42fe-4bcf-b1f7-0a5f5047ba2b)

**Comment by srg74** [comment]
Should work fine with this settings. What version of board are you using?

**Comment by spad** [comment]
I'm using v3.0 from pcbway.
I already cheked the build and the components values. All the components are from DigiKey from the BOM.
![PXL_20241205_135937279](https://github.com/user-attachments/assets/35ca6669-0c20-403f-862f-e4e6d5468892)

**Comment by srg74** [comment]
Your board looks ok. Signal levels for relay are ok. Only things could be wrong is MosFET and diode.
