### ISSUE TITLE
Replacement for a 1000uf 25v capacitor

### ISSUE THREAD

**Issue by slakin** [srg74/WLED-wemos-shield#17]
Hi, thanks for your project. I already done several shields and they works flawlessly. 
My question is can I use 1000uf 16v capacitor instead of 25v? 25v version is too high for my enclosure.

**Comment by srg74** [comment]
Basically if you using 5V LED strips you can use lower voltage capacitor. General rule for capacitors is (powers supply voltage)x2 = capacitor voltage.
