### ISSUE TITLE
3D images of the assembled PCB?

### ISSUE THREAD

**Issue by rboers72** [srg74/WLED-wemos-shield#19]
Could you please provide me with the 3D images of the assembled PCB (no-audio and audio) in F3B or any other format? That would be great. Thank you.

**Comment by srg74** [comment]
Which version you asking?

**Comment by rboers72** [comment]
version 1.2

**Comment by srg74** [comment]
I prepared files for you. If you present at WLED discord channel please PM me @serg74.
