### ISSUE TITLE
Do you sell finished WLED-wemos-shield?

### ISSUE THREAD

**Issue by dioem1985** [srg74/WLED-wemos-shield#2]
Hello, sorry I choose this way to write to you. Do you also sell assembled WLED-wemos shields? Would love to buy a few from you. Do you have an email address? Would also leave mine here if they sold me one or more WLED-wemos-shield. I come from Germany and have only started soldering since last year.
Sincerely yours
dioem1985

**Comment by srg74** [comment]
Hi. This is open source project and you can ask questions. As of right now I don't assemble and sell shield. All my intend was to help WLED community with affordable DIY solution. Especially for the beginners. Nova days most of the projects using SMT components and for the beginners very difficult handle them and expensive.
You can order PCB and parts very cheap. Talk to your friends DIYers and assemble few PCBs for yourself and friends - have fun. People doing classes for the assembly and fun. Old people who never hold soldering iron in their hands. Participate https://wled.discourse.group/ and you find people from Germany who already doing shield or think about it.
If nothing above is good for you. You can buy similar board from Quinled.
Best regards.

**Comment by dioem1985** [comment]
Thank you for your reply

**Comment by dioem1985** [comment]
Hi,
I just ordered the pcb from pcbway, thanks for that. Can you please give me a precise list of the parts you need, with the exact description of the parts? Thank you very much for your effort.
Sincerely yours
dioem1985

**Comment by srg74** [comment]
Did you navigate repository? https://github.com/srg74/WLED-wemos-shield/blob/master/resources/BOM.pdf

**Comment by dioem1985** [comment]
Unfortunately I missed that.  Thank you very much.  Sorry if I annoy you so much.

**Comment by srg74** [comment]
Np

**Comment by srg74** [comment]
Solved

**Comment by Joshfindit** [comment]
I found this issue by searching for PCBWay, and wonder if you could share the complete project through https://www.pcbway.com/project/shareproject/

Two benefits:
1. People would be able to order PCB and all parts at the same time
2. There could be an SMD version that people could order assembled for extra cost

**Comment by netmindz** [comment]
+1 for shared project
