### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by CWempe** [srg74/WLED-wemos-shield#23]
First of all, thank for this project! 👍 

I recently ordered 10 pieces of the v1.2 board.

Know I see there is a version v1.3. 😮 

It would be great if there was a changelog to see what was changed (and why).
It is hard to check for the changes yourself since Github cannot show `diff` of binary files. 😉

**Comment by srg74** [comment]
Good idea! Thank you for your tip. There is no significant difference between v1.2 and v1.3. All main functionality remain the same. Difference only pin D5 on Wemos can be used with on board IR receiver instead as of additional button and D3 pin is used now with on board momentary switch.

**Comment by CWempe** [comment]
Thanks
