### ISSUE TITLE
Radial Fuse Alternative

### ISSUE THREAD

**Issue by Ryanb369** [srg74/WLED-wemos-shield#26]
First off, thanks for making this awesome solution and allowing it to be open! I've got a question about the 16v radial fuse. Is there an alternative to this, I'm finding the availability of these are slim. Thanks in advance!

**Comment by srg74** [comment]
Why they not available?
Alternatives: MF-RHT070-2, PTR016V0090-BK, B59955C0160A070, RUSBF090-2, MF-RHT070-0, YQZ120N1.00

**Comment by Ryanb369** [comment]
I may have been looking in the wrong places, I appreciate the quick response. Would a 16v 1A Work?

**Comment by srg74** [comment]
I guess no harm. Main concern is time it should trip. Shorter time is better.

**Comment by Ryanb369** [comment]
Gotcha, so within 500-700mA is best practice?

**Comment by srg74** [comment]
Yep

**Comment by Ryanb369** [comment]
Thank you!

**Comment by zsolesz79** [comment]
I'm struggling to find some of the components locally...  :( One of them is the PTC, so how much would be the suitable time to trip value that I should look for?

Another one is the 10uF ceramic capacitor? Can I go with a tantalum or a low ESR electrolytic instead?
