### ISSUE TITLE
Bare minimum - Not working

### ISSUE THREAD

**Issue by Dragi2k** [srg74/WLED-wemos-shield#27]
Hello,

i have Build the Board and its not Working.
Is it Possible that "R8" is needet ?

**Comment by w00000dy** [comment]
Hello,
R8 is not needed for Bare minimum. Can you give more informations? What exactly is not working? Can you send a picture of your assembled board? What are the results of the [check](https://github.com/srg74/WLED-wemos-shield/wiki/Check) steps?

**Comment by Dragi2k** [comment]
Nur if i shorten r8 it works fine 🤔
![Uploading 1606245926359932586524304444191.jpg…]()

**Comment by Dragi2k** [comment]
![IMG_20201124_203845](https://user-images.githubusercontent.com/63540526/100143187-3e96b100-2e95-11eb-9b36-7b12c3ad59c2.jpg)
![IMG_20201124_203928](https://user-images.githubusercontent.com/63540526/100143210-46eeec00-2e95-11eb-9ec4-3d3de3b17bea.jpg)
![IMG_20201124_203956](https://user-images.githubusercontent.com/63540526/100143223-4ce4cd00-2e95-11eb-81ac-ac9c350a5601.jpg)
And the Fuse holes are also wrong, but i dont know, ob this false by pcb-way is

**Comment by srg74** [comment]
Some how resistor R8 150 Ohm. You do need this resistor for minimum configuration. Look at BOM v1.3 because your board is v1.3. You can find archive here https://github.com/srg74/WLED-wemos-shield/releases/tag/v1.3. Please when you test install fuse for LED strip. On photo socket for fuse is empty.

**Comment by Dragi2k** [comment]
I know, fuse is in the way 😉
But what is with the holes of the Fuse holder?
![IMG_20201124_172633](https://user-images.githubusercontent.com/63540526/100150748-693a3700-2ea0-11eb-9091-80898ad213db.jpg)

**Comment by srg74** [comment]
Where did you order your PCB?

**Comment by srg74** [comment]
![WLED_shield_v1 3](https://user-images.githubusercontent.com/28492985/100153588-527ceb80-2e72-11eb-8851-bdb13d1cabad.png)

**Comment by Dragi2k** [comment]
Over your link, on pcb-way

**Comment by srg74** [comment]
In this case you have to contact PCBway and explain that your board came not routed. They have to repeat your order it's their responsibility.
