### ISSUE TITLE
Resistors R1 / R8

### ISSUE THREAD

**Issue by Ryanb369** [srg74/WLED-wemos-shield#28]
i may be blind, but the value for R8 is not listed on BOM. I can't seem to find R1 on the board either. Thanks for the info in advance.

**Comment by w00000dy** [comment]
Hello,
R1 is next to the 8-Pin header. Where do you see R8? I think R8 doesn't exist, or am i wrong?

**Comment by Ryanb369** [comment]
![image](https://user-images.githubusercontent.com/60478240/100147235-142efe80-2e69-11eb-854d-0c06d9ebb229.jpeg) R8 is right in the middle, could that be R1?

**Comment by w00000dy** [comment]
Oh sorry. I don't have the new v1.5 board. I just have the older ones. But I'm sure @srg74 can help here. 😃

**Comment by srg74** [comment]
Resistor you asking is not R8 but R2 150 Ohm

**Comment by Ryanb369** [comment]
Is there a value for R8? Or is this not needed

**Comment by srg74** [comment]
Please read right above :)

**Comment by srg74** [comment]
Errors fixed
