### ISSUE TITLE
D1 not booting when connected to 12v

### ISSUE THREAD

**Issue by Ryanb369** [srg74/WLED-wemos-shield#29]
The D1 blinks once and goes dark. Led indicator on wemos-shield  is lit up. D1 is fine when connected via usb. Unsure of why, ![image](https://user-images.githubusercontent.com/60478240/100252944-80b00900-2f0e-11eb-8544-b51efe38fe88.jpeg)

![image](https://user-images.githubusercontent.com/60478240/100253021-99202380-2f0e-11eb-8e41-9a2b74d04318.jpeg)

**Comment by w00000dy** [comment]
Hello,
what are the results of the [check](https://github.com/srg74/WLED-wemos-shield/wiki/Check) steps?

**Comment by Ryanb369** [comment]
All the voltages are as they should, at jumpers and board inputs.

**Comment by srg74** [comment]
Please remove push button from the board. Early batch of PCBs have error. If you comfortable to cut traces I can explain what to cut. And put power selector jumper in 12V position

**Comment by Ryanb369** [comment]
I'll desolder the button, i believe i have pcb 1.5

**Comment by srg74** [comment]
So is it working now?

**Comment by srg74** [comment]
Also for quick response you can reach me https://discord.gg/KuqP7NE  as @Serg74

**Comment by kallejoken** [comment]
> So is it working now?

I have exactly the same problem with version 3.0, I didn't solder the push button. Do you have any help?

no matter whether 5v or 12v connection

**Comment by srg74** [comment]
Version 3.0 don’t have errors and works for 2 years without problems

**Comment by kallejoken** [comment]
> Version 3.0 don’t have errors and works for 2 years without problems

yes exactly, but only if I apply the fix as described here https://github.com/srg74/WLED-wemos-shield/issues/107

**Comment by srg74** [comment]
Problem here is most likely due to different design of mini board used. But in this post you can find solution for the issue.
