### ISSUE TITLE
IR receiver input (feature request)

### ISSUE THREAD

**Issue by kareem613** [srg74/WLED-wemos-shield#3]
WLED has support for IR remotes. 
I think this would be a great addition to this board. Just requires 3 pins to support a tsop38238.

**Comment by srg74** [comment]
Thank you for your suggestion. Actually I found that IR receiver working better on pin D5(GPIO14) and this pin is exposed on the board. Next to pin you will find 3.3V header and you can connect just IR receiver (without board) to shield. Plus IR KY-022 or TSOP38238 is cheap without pcb and you can install IR in any convenient place. Only downside of such a setup you have to compile your custom firmware for GPIO14.

**Comment by srg74** [comment]
Answered
