### ISSUE TITLE
Step file for full board layout

### ISSUE THREAD

**Issue by ubergeekseven** [srg74/WLED-wemos-shield#32]
Thank you very much for this project. It has simplified my setup so much and I'm in the middle of replacing all my controllers with this one.
That being said, of you could upload a 3d format of the populated board, it would be much easier to create enclosures quickly.
If you do upload one, step output would be the easiest to use in most cad programs. Stl or obj output will produce ok results but, it's hard to work with in cad most of the time. With step, I could easily project from components to sketches. 

I'm not sure what program you used for creating the board but, if eagle, then fusion can natively import the project and enclosures are a part of that workflow. If something else, I'm not sure what output options it has. The renderings make me think it's possible to output something useable though.

Again, thanks very much for the work you've put in already. It's very much appreciated. I can finally hand out things I make with this and expect a normal person to be able to figure it out.

**Comment by srg74** [comment]
Added [STEP file](https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Enclosure)
