### ISSUE TITLE
Capacitor C5

### ISSUE THREAD

**Issue by gtrs** [srg74/WLED-wemos-shield#35]
According to the datasheet for the [VXO7805-500](https://eu.mouser.com/datasheet/2/670/vxo78_500-1774699.pdf) the ceramic cap on the 5V side (C5 in the WLED-wemos-shield) is recommended to have 22µF (see C2 in Fig. 1 / Table 1 on page 6 of the datasheet). I don't know if that is important here, as there is also cap C6 on the output side with higher capacity.

**Comment by srg74** [comment]
If you look at revision info on data sheet changes was made last year after I release my board. I don’t see it’s necessary to upgrade to 22uF, but you did no harm will be done. Just a little more smoother power.

**Comment by srg74** [comment]
Stale
