### ISSUE TITLE
Where is Dallas Temperature?

### ISSUE THREAD

**Issue by ghost** [srg74/WLED-wemos-shield#36]
I've some boards with all the options and was under the impression that the temperature would be displayed in the info section as well as mqtt (not tested).

I've uncommented the 

  #For Dallas sensor uncomment following 2 lines
    OneWire@~2.3.5
    milesburton/DallasTemperature@^3.9.0 
    
    Complied for both d1 mini (clone) and my ESP32 and can't see it anywhere

**Comment by srg74** [comment]
Uncommenting libraries is not enable usermod. Better if you use precompiled bin files from this repository. If you want to compile your code use my WLED fork this branch https://github.com/srg74/WLED/tree/WLED_wemos_shield

**Comment by ghost** [comment]
I've been using your fork as I could not see it using your binary. I can see the temperature via mqtt, so I know it's working.
![Capture](https://user-images.githubusercontent.com/55344114/104752002-03ef1d80-574e-11eb-8400-2d053ec2f074.PNG)

**Comment by srg74** [comment]
Yes it’s work only over mqtt. I don’t implement yet GUI part. It’s was an error there which was fixed recently but I don’t have a time to look into GUI part.

**Comment by ghost** [comment]
Awesome. At least it's not something I did. Love your shields. Got some outdoor ones to build for the summer.

**Comment by yousaf465** [comment]
@srg74 how do I setup mqtt for this? which topics to use?
