### ISSUE TITLE
Link to wiki on pcb

### ISSUE THREAD

**Issue by w00000dy** [srg74/WLED-wemos-shield#37]
Hey,
what about putting an link and qr-code to wiki on pcb.
I could look like this:

![grafik](https://user-images.githubusercontent.com/27882680/106360091-e659b080-6316-11eb-88e0-6e0a27633838.png)

This is the link i used: https://bit.ly/3oycoqm
Here are the qr-code: [qr-code.zip](https://github.com/srg74/WLED-wemos-shield/files/5898187/qr-code.zip)

**Comment by srg74** [comment]
Added to recent design
