### ISSUE TITLE
Shelly RGBW2 OTA and button not working

### ISSUE THREAD

**Issue by memphisdj** [srg74/WLED-wemos-shield#38]
Hello, I have successfully flashed the shelly wled firmware. However, I cannot get the button to work or the OTA update. The OTA fails with tasmota and wled firmware. Please advice.

**Comment by w00000dy** [comment]
What shield version do you use?

**Comment by memphisdj** [comment]
Hi, I was unaware that I needed the shield, I am using the rgbw2 standalone. Although, this should not affect OTA.

**Comment by srg74** [comment]
Hello. Definitely you don’t need shield. As I understand you found firmware for Shelly device. This is curtesy firmware for specific device. Your Shelly device might have different pinout. Regarding OTA - WLED is not supporting OTA for devices with memory less than 4mB.

**Comment by memphisdj** [comment]
Hi, thanks for the input. I am using your  firmware from this repo. So, the build in inputs for the shelly are not mapped into it? Noted about the OTA.

**Comment by srg74** [comment]
It's mapped but as I mentioned your shelly might have different pinout. You can try compile yourself from here https://github.com/srg74/WLED/blob/ShellyRGBW2 This branch is a source for a bin file located here.

**Comment by memphisdj** [comment]
Thanks, that's all the info I needed.
