### ISSUE TITLE
PCB v2.0 setup issue

### ISSUE THREAD

**Issue by ChristophA** [srg74/WLED-wemos-shield#39]
Hi,
thank you very much for this cool project! I recently ordered come PSBs v2.0 and the required parts. While assembling a minimum setup I struggled to find the correct place for the fuse F2. There's no lable on the PCB for F2. But after a while i figured out to place in on the right hand side of D2. Maybe it's worth to add a lable for F2 on the PCB!?

A Wemos D1 Mini (also tested with D1 Mini pro) is now starting and accessible viw the webinterface. I confiugre the relay to use pin / GPIO 12, works as expected. LED out (DI) is configured to use pin / GPIO 2. But I cannot light any LED. Not sure if my setup is correct. I've also added R1 and R2, but still no light. Firmware is the latest v0.12.0-b3

Is there anything missing?

Many thanks for any hint!

PS: Still waiting for the fuse holder, therefore I'vs added a short cable just for testing.

![PCB v2 0](https://user-images.githubusercontent.com/5113802/112748485-24441f80-8fbc-11eb-84ad-9f1bf13d0bb9.jpg)

**Comment by srg74** [comment]
First  of all your IC is different from which project is using. 74HCT126 is a buffer not a shifter. I don't think it will work.

**Comment by ChristophA** [comment]
I've double checked everything 10 times. Everyting but this chip...
Thank you very much, I'll replace it wit a 74AHCT125. For some reasons 3 of these 126ers are in the box with the 125ers. Don't no were thes come from.

I'll report back once replaced.

**Comment by ChristophA** [comment]
All good now! Thanks again for pointing me in the right direction!
