### ISSUE TITLE
1N4148 Digikey does not exist

### ISSUE THREAD

**Issue by w00000dy** [srg74/WLED-wemos-shield#4]
Hello,
in your BOM the Digikey of 1N4148 does not exist.
Can you update this?
Also it would be nice if you create a shopping cart link for digikey. :)

**Comment by srg74** [comment]
Just for now part# is 1N4148-P-TAPGICT-ND. Later I will update BOM

**Comment by w00000dy** [comment]
I ordered [this](https://www.digikey.de/product-detail/de/1N4148/1N4148FS-ND/458603?utm_medium=email&utm_source=oce&utm_campaign=3026_OCE20RT&utm_content=productdetail_DE&utm_cid=1343331&so=64601622&mkt_tok=eyJpIjoiTXpoaU9Ea3dZMkppTVdaaSIsInQiOiIrbmxNXC9MVkltYjZkZTVucTI4XC9LdWJ6UFdpc3FWelpsS3NDem1wYmlaaVcxWm1jYmx6bGJCMVpsRXlzdnloXC9tbVpVSkpjSDhSZWxkakhoWlFpMHNNbFl4cDhEdVlzMit5dndsa0NTWW1rXC9cL0NIcEY1SDBjaEFvRkZ6OGxCVnNNIn0%3D). Can I also use it?

**Comment by srg74** [comment]
BOM corrected
