### ISSUE TITLE
Can I modify the PCB?

### ISSUE THREAD

**Issue by frizzby** [srg74/WLED-wemos-shield#41]
Hi, thanks for the work you put into this.
I'd like to make some minor changes to the board to allow for locally available parts.
Are the source files of the PCB available for modification?

**Comment by srg74** [comment]
Unfortunately source files is not available for changes from third part due to wide usage of the board. I’m trying to keep consistent design across releases for all users who already have early versions. Schematic is open source and you can use it to create your own board design.
