### ISSUE TITLE
Mini Shield Gerbers

### ISSUE THREAD

**Issue by ejdprops** [srg74/WLED-wemos-shield#42]
Is it possible to get the gerbers/schematic for the mini shield?  I don't see them on the repo.

Thanks

EJ

**Comment by WoodyLetsCode** [comment]
You can find gerbers here: https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Gerbers

Schematic is here: https://github.com/srg74/WLED-wemos-shield/tree/master/resources#shield-pcbs-and-scematic

**Comment by ejdprops** [comment]
those are for the regular board with the relay on it.  I was looking for the mini shield
![mini](https://user-images.githubusercontent.com/47348053/113619271-686b9b80-961e-11eb-8103-d90774a0b494.jpeg)
