### ISSUE TITLE
12v Support

### ISSUE THREAD

**Issue by florianmulatz** [srg74/WLED-wemos-shield#47]
Hi,

i've ordered these ones from aliexpress (https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.buyer_leave_review.0.0.1fbe6c1bQkU1Ve&orderId=8130740139745887&productId=32848919879) in 10µF (the only "technical" difference from my point of perspective is that they are suitable for up to 50V) for 12V Compatibility - they does not fit perfectly but it's acceptable. I guess these should also work as C4, C5 right.

I'm asking because after I have soldered them and put the Jumper to 12V and added a 12V PSU - the esp does not light up anymore.

Maybe it's a misunderstanding and the 12V Support is only supported for OUTPUT.

Cheers

**Comment by shortbloke** [comment]
Did you also install PS1 a VXO7805-500 DC to DC converter to provide 5V to your MCU when using a 12V PSU and 12V LEDs. Per: https://github.com/srg74/WLED-wemos-shield/wiki/Options#1-manual-power-selector-with-jumper-you-can-manually-switch-between-5v-or-12v-power-supply-and-leds
The AliExpress link doesn't work for me, so I can't see what caps you used for C4 and C5. Also ensure you mount the VXO7805-500 the correct way round.

You should also check the correct voltage is getting to the MCU following the steps: https://github.com/srg74/WLED-wemos-shield/wiki/Check

**Comment by florianmulatz** [comment]
ah - that looks to be the culprit! I've completely overseen that component. this should be the correct link for the caps --> https://de.aliexpress.com/item/32848919879.html?spm=a2g0s.12269583.0.0.7ad86a4aEK2JGo. Hm would be challenging to add the dc-dc converter as well because of the too big caps now - maybe i'll work with some small extension-cables.

**Comment by shortbloke** [comment]
The DC-DC converter does come with 3 right angled header pins, so it can be elevated off the board a little which might provide enough clearance for your larger capacitor pair.

**Comment by florianmulatz** [comment]
Sounds legit. Do you think the caps will fit? - thx for your  help indeed!

**Comment by srg74** [comment]
> Sounds legit. Do you think the caps will fit? - thx for your help indeed!

Please, for troubleshooting come to WLED discord and we can resolve it quickly.

**Comment by florianmulatz** [comment]
connected :) - thx in the meantime
