### ISSUE TITLE
How do I enable the OLED display?

### ISSUE THREAD

**Issue by harwalan** [srg74/WLED-wemos-shield#48]
I just bought a few of these but I'm not sure how to enable the OLED display.  Do I need a custom build of WLED for?  Or is it an option to configure somewhere?  thx!

**Comment by srg74** [comment]
Could you please come over to WLED discord channel? https://discord.gg/KuqP7NE I will answer your questions quicker. I need more details.

**Comment by harwalan** [comment]
Sure!  I just jumped on there.  Where is the best place to post the question?

**Comment by srg74** [comment]
#learning will be good. Ring me @Serg74
