### ISSUE TITLE
Part list EU Shop

### ISSUE THREAD

**Issue by kmplngj** [srg74/WLED-wemos-shield#49]
Hello,

would somebody help me getting a part list together for shopping in the EU? I think Reichelt would be a good source. https://www.reichelt.de/?LANGUAGE=EN

Thanks
Jan

**Comment by srg74** [comment]
In BOM list you have all manufacturers item numbers. You can search on preferred supplier website by this numbers. In Germany Digi-Key is working just fine and in BOM you have all Digi-Key item numbers too. Only for Digi-Key order you need ordered for 50€ to have free shipping. Their part quality and service are great.
