### ISSUE TITLE
10k OHM Resistor too big

### ISSUE THREAD

**Issue by w00000dy** [srg74/WLED-wemos-shield#5]
Hey,
it seems that the 10k OHM Resistor is a little bit too big for the holes.
![IMG_20200622_184935](https://user-images.githubusercontent.com/27882680/85336108-63e65400-b4de-11ea-97ff-ea6aacc9a67c.jpg)
It's quite a struggle to get it fit into the holes.
![IMG_20200622_230005](https://user-images.githubusercontent.com/27882680/85336283-a7d95900-b4de-11ea-894f-bdfee387af10.jpg)
The 4.7k OHM Resistors have the perfect size for the holes.
Maybe you choose 10K OHM resistors in the size of the 4.7k OHM resistors in your BOM, if possible. 😄

**Comment by srg74** [comment]
Thank you for your report.
BOM now is updated to correct values https://github.com/srg74/WLED-wemos-shield/blob/master/resources/BOM.pdf

**Comment by w00000dy** [comment]
Okay, thank you! 😄
