### ISSUE TITLE
Setting leds not work

### ISSUE THREAD

**Issue by sagaardu** [srg74/WLED-wemos-shield#50]
Hello,

I am trying to test this version but it is impossible to modify the number of LEDs in the configuration.

Can you take a look at it?

Greetings

**Comment by srg74** [comment]
> I am trying to test this version but it is impossible to modify the number of LEDs
You not mentioned what version you used. Since v0.12 you set quantity of LEDs per pin not a total.

**Comment by sagaardu** [comment]
The version I'm using is your compilation to test the usermod via GUI (0.12.2-bl4 "Ryujin")

As you well indicate, you have to configure the number of total LEDs per pin, that value does not allow modifying it, it is at 30 LEDs and it does not allow changing it.

Neither can you modify the usermod presets such as segment-delay-ms: and on-time-s: when you give it to save it leaves them as is

**Comment by srg74** [comment]
Please, use official firmware. The one you try is dev fork. https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/WLED_wemos_shield/v0.12.0_2106271

**Comment by sagaardu** [comment]
Hello, I have installed the version you indicate and the problem of configuring the LEDs has been solved.

What still doesn't work is being able to change parameters from the staircase:

- delay-ms parameters:
- on-time-s:

**Comment by huggy-d1** [comment]
Are you sending the parameters via browser like the readme.md for the staircase usermod suggests?

**Comment by sagaardu** [comment]
No, I am trying to adjust it from the GUI

**Comment by sagaardu** [comment]
via curl not working either

```
 curl -X POST -H "Content-Type: application/json" -d '{"staircase":{"segment-delay-ms":1000,"on-time":10}}' 192.168.142.63/json/state

{"success":true}
```

**Comment by srg74** [comment]
For Json you have to ask in #dev-general at WLED discord channel. They have updated some code related to Json.
