### ISSUE TITLE
What's about the possibility to use more than one stripe with a single esp32

### ISSUE THREAD

**Issue by Aussiedler** [srg74/WLED-wemos-shield#51]
Hi, I have a question about your board. If I understood correctly, the power supply for the board itself can be selected up to 24V. LED strips there are but only 5-12V right? The DC-DC converter converts only the power for the esp32 right? The stripe will get the full 5-24V which is specific from the selected power supply, right?

I was looking for a variant with an ESP32, because with this it should be possible to connect 10 strips simultaneously and 4 strips productively. Well your board actually fulfills all wishes. But with you I see only the connection option for one strip, or am I mistaken here?

Thanks for the help!

**Comment by srg74** [comment]
Hi. Yes you understood correct. Board able to handle 5V or 12/24V power supply and strip must be same voltage. Means 5V PS and 5V LED strip or 12V power supply and 12V LEDs. Regarding quantity of the connected strips 4 strips maximum if you configure regarding your setup. In this case sound reactive feature with microphone is not possible. But possible with linear audio input. Actually quantity of the strips is not beneficial only make sense if your setup is required connections in one point.

**Comment by Aussiedler** [comment]
Thanks for the quick feedback! In my case I have a large room with 2 supply points where 5x2,5mm² cable are installed. A total lenght of 30m LED strips must be connected. I had considered using 2 WLED controllers which control 2 lines each. So I would have per line 7-8m or 420-480 LED pixels per line. The ESP32 should be able to handle that, right?

The question is, how is another stripe connected to your board?

**Comment by srg74** [comment]
Here is pinout for entire board https://github.com/srg74/WLED-wemos-shield/blob/master/resources/Images/wiki/Wemos_shield_pinout.pdf
