### ISSUE TITLE
Sound reactive build 2108010 bricks ESP32

### ISSUE THREAD

**Issue by lanman1** [srg74/WLED-wemos-shield#53]
OTA build 2108010 bricked ESP32 using both with/without display.  Had to re-flash with USB

**Comment by srg74** [comment]
I will check firmware and if this fixable I will update files

**Comment by lanman1** [comment]
Thanks!  No problem, just letting you know.

**Comment by srg74** [comment]
Fixed :)

**Comment by lanman1** [comment]
Must be me, When I try to do an OTA update of my TTGO ESP32, it bricks with
the predone bin.  I then have to reflash with USB.

**Comment by srg74** [comment]
Again? With new bin files?

**Comment by lanman1** [comment]
yes.  I have run 13. on this before and it is ok.  If I'm on 12.0, I upload the bin via OTA and the ESP just lock up at reboot.  No relay click, just locks.  It is the TTGO board and not NodeMCU

**Comment by lanman1** [comment]
The non-SoundReactive v0.13.0-b2/esp32_no_mods.bin works ok.  But both SoundReactive bin do not.

**Comment by srg74** [comment]
TTGO ESP32 T7 v1.3?

**Comment by lanman1** [comment]
Yes.  As information, it appears to be related to presets.  I did a factory reset and was able to load the soundreactive bin ok but there is no option to backup/restore presets.  I flashed back to the non SoundReactive and preset backup/restore is there.

**Comment by srg74** [comment]
So you did fix your board and bin files is ok? Presets backup your_wled_IP/edit. Btw one more file added.

**Comment by lanman1** [comment]
There seems to be an issue with soundreactive bin files.  There is no backup/restore option in the soundreactive bins and if presets exist before flashing soundreactive, the board locks up.

**Comment by srg74** [comment]
Yep, I can confirm. In this case have to report to sound reactive fork.

**Comment by lanman1** [comment]
Thank you.  Let me know if I can help test, thank you for posting the .bin(s)

**Comment by srg74** [comment]
I already posted question to devs. If glitch will be fixed I'll post result here.

**Comment by srg74** [comment]
After some clarification I found that bin files is OK. To back up presets. you go to IP_wled/edit -> right click on file presets.json and save file.

**Comment by lanman1** [comment]
Ok.  There still is the issue of if presets exist during ota upgrade it
will brick the board.

**Comment by srg74** [comment]
I will dig further. Hopefully there is explanation to this issue.
Here is answer from one of the devs:
@Harry Baas — Today at 3:31 PM
I would first advise to sanitize the presets.json by copy paste to editor and do search and replace (all double spaces > ""), copy paste back and save.
I Have not encountered a situation where presets.json was related to OTA fail. Can't really say anything useful except try to get presets.json less corrupted.

**Comment by srg74** [comment]
Have been fixed.
