### ISSUE TITLE
Shield CAD incorrect for board version 3

### ISSUE THREAD

**Issue by invalidflaw** [srg74/WLED-wemos-shield#56]
The version 3 of the board is 2mm larger than the CAD model provided on GrabCAD. The CAD model measures 61.27mm in length and my caliper measures my tindie purchased board at 63.24mm. It seems like the board changed size slightly.

**Comment by srg74** [comment]
There is 2 SMD versions due to parts shortage. You have longer one which use bigger terminal connector and 2mm longer. All components stay in place but board outline and mounting holes is further by 2mm (on terminal connector side).
