### ISSUE TITLE
Wrong value for F2 & other PTC fuse?

### ISSUE THREAD

**Issue by w00000dy** [srg74/WLED-wemos-shield#6]
Hello,
the value of F2 (RUSBF075-APHFCT-ND) in your BOM is _30V 500mA_, but it is a **6V 750mA** fuse.
And aren't 6v a little bit too low? For example when somebody accidentally connects it to 12V :sweat_smile: it is possible that electricity arcs over the fuse.
Wouldn't this PTC fuse be better?
DigiKey: [507-2375-ND](https://www.digikey.de/product-detail/de/bel-fuse-inc/0ZRG0075FF1E/507-2375-ND/9468224)

**Comment by srg74** [comment]
Thank you for your correction. Fixed in update.

**Comment by w00000dy** [comment]
How do you make this BOM pdf file?

**Comment by srg74** [comment]
I'm a Mac user so using a Numbers for spreadsheets. On DigiKey website I'm creating BOM file then exporting as CSV and then editing in Numbers to what you see. After just instead of printing save as PDF. Done!

**Comment by w00000dy** [comment]
Can you also export it as .XLSX-File, so other users can edit it with excel?

**Comment by srg74** [comment]
I don't who else need to edit this file, but I did a copy in XLSX
Plus check out https://github.com/srg74/WLED-wemos-shield/blob/master/resources/WLED_Wemos_shield_Digikey.csv

**Comment by w00000dy** [comment]
Thank you! :smile:
