### ISSUE TITLE
Wifi connectivity problems with 12v supply

### ISSUE THREAD

**Issue by crackston** [srg74/WLED-wemos-shield#62]
I am not able to remain connected to WLED hotspot when it runs on 12vdc. If I keep my phone less than 6" from the ESP32 it will stay connected, but any further it will disconnect immediately. WLED is not able to connect to a wifi access point with a signal strength of 75%. If I move the jumper and operate the device on 5v only it is able to connect with no problem though walls and at least 30 feet away (I did not test greater distances). 

My voltage source is a 400W Dell power supply. I have alternatively tried a 12vdc 4A plug-in switching power supply. I have two identical WLED-wemos-shields that behave exactly the same. When the board is powered with 5V and 12V (jumper removed) from the Dell PS it is able to connect and remain connected to wifi and control LED's without problem. 

I tried wrapping the K78L05 in electrical tape and then aluminum foil in order to test if that is the source.  The wifi signal seems to be better and will remain connected to my phone up to 12 feet now. I still need to ground the foil to make a better shield.  Does anyone have recommendations for a better shield?

The K78L05-1000R3 is listed as a CISPR 32 Class B which is a decent EMC rating for an in-house device, so it doesn't make sense. The p-p ripple on the 5v output was less than 30mV when I tested on an oscilloscope. 

Has anyone else noticed this kind of issue?

**Comment by srg74** [comment]
I don't even know what to answer you. You the first one who report such a problem. Buck converter shouldn't cause big interference to ESP antenna. In AP WLED is not stable but when connected to a network no issues reported.
