### ISSUE TITLE
Gerber files to adjust to WT32ETH-01

### ISSUE THREAD

**Issue by LeonVos** [srg74/WLED-wemos-shield#63]
Hi,

Great project  !
But do you share your gerber files??
I like to adjust it for use with the WT32ETH-01 ;-)
Or maybe you can? An converter board would also be great.

Thx, Leon Vos

**Comment by srg74** [comment]
Hi! Ethernet board have different form factor and to make that board to work with my shield will take complete redesign. All files necessary to make design which will fit Ethernet board are posted here.
