### ISSUE TITLE
soundReactive_d1_mini.bin / v0.13.0-b3 / No Alexa ???

### ISSUE THREAD

**Issue by bennony** [srg74/WLED-wemos-shield#66]
soundReactive_d1_mini.bin / v0.13.0-b3

Hi, everything works quite well so far, but I can't get the ESP connected to Alexa. The checkmark for Emulate Alexa device is set. Restarting Alexa and searching again had no success either

**Comment by srg74** [comment]
All questions related to functionality of particular firmware have to be addressed to developers. I'm only compiling code and publish to my repository for users convenience.
You can try latest code here https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/Sound_reactive/v0.13.0-b6

**Comment by bennony** [comment]
I tested the b6 (aircoookie) (ESP 8266 support) Alexa works, the sound-Reactive B6 unfortunately does not support 8266, the 13.0 b4 was the last one here (however, alexa seems to be deactivated here in the script) I would be happy if you still have the b6 finished for the ESP8266 (with Alexa Enabled ;-)) the sound reactive is a fine thing.

**Comment by srg74** [comment]
Next update of sound reactive to b6 is not depend on me but on SR development team. As soon they release new update on ESP8266 fork I will compile and post new bins.

**Comment by bennony** [comment]
Great news ;-) and great work
