### ISSUE TITLE
WS2801 Config

### ISSUE THREAD

**Issue by macjex** [srg74/WLED-wemos-shield#68]
Hi everyone, 

is the Libary for the 5v WS 2801 included in the firmwares ? 

Because I am trying to connect the strip but it does not want to work. 
(the ws2812 works with no problem)  changing the GPIO 3 to 1 have no effect

thanks in advance

**Comment by srg74** [comment]
What board are you using?

**Comment by macjex** [comment]
Apologies :)

Wemos d1 mini

**Comment by srg74** [comment]
Did you configured soldering jumpers according to Wiki?

**Comment by macjex** [comment]
Oh my .... I forgot ... I will get that Sorted 

Thank you ! And sorry for unnecessary post.
