### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by darkcloud784** [srg74/WLED-wemos-shield#69]
Is the V3 version of the sheild compatible with the 30 pin (15x2 pins per row https://www.amazon.com/gp/product/B08D5ZD528/ref=ppx_yo_dt_b_asin_title_o06_s04?ie=UTF8&psc=1)  development ESP32 boards? I only see references to the 4 pin row versions and twilightlords which is out of stock.

**Comment by srg74** [comment]
It's not compatible with 15x2 boards. Only compatible boards are here https://github.com/srg74/WLED-wemos-shield/wiki

**Comment by darkcloud784** [comment]
> It's not compatible with 15x2 boards. Only compatible boards are here https://github.com/srg74/WLED-wemos-shield/wiki

Thanks for the confirmation.
