### ISSUE TITLE
R4 can't be 10K

### ISSUE THREAD

**Issue by wz2b** [srg74/WLED-wemos-shield#72]
I built 10 of these boards and they work really well.  One note that's probably a schematic/BOM error is R4 can't be 10K if you want the LED to work.  For 10 mA or so you probably want something more like 270 ohms.  For a power indicator, less current would probably be fine too - 330 would work.

**Comment by srg74** [comment]
I understand  your concern. 10K is used for very dim LED.

**Comment by wz2b** [comment]
Oh okay - I did not realize it was intentional.  10K with say a 3V drop
across it is 300 microamps - I'm surprised you'd be able to see that at
all.  But perhaps in a very dark room you would.

Fair enough!  Thanks for the reply.

**Comment by wz2b** [comment]
Oh okay - I did not realize it was intentional.  10K with say a 3V drop across it is 300 microamps - I'm surprised you'd be able to see that at all.  But perhaps in a very dark room you would.

Fair enough!  Thanks for the reply.
