### ISSUE TITLE
WLED_0.14.0-bl0_ESP32_staircase_usermod.bin

### ISSUE THREAD

**Issue by Darozas** [srg74/WLED-wemos-shield#74]
Hi 

Thanks for sharing this. i have installed this bin file but only can get 2 stairs to lit up.

Got all set as per 

"In the WLED UI, configure a segment for each step. The lowest step of the stairs is the lowest segment id."

All segments are there but not working correctly. 

Can you please point m out in right direction

Regards

**Comment by srg74** [comment]
Thank you for using my repo. Unfortunately I'm not author of staircase usermod. My job is only compile and publish firmware for people who not able to do by themselves. For help you can ask author or join WLED Discord https://discord.gg/KuqP7NE or WLED Discourse group https://wled.discourse.group
