### ISSUE TITLE
D2 not working

### ISSUE THREAD

**Issue by DarthWeber** [srg74/WLED-wemos-shield#77]
Hi, i have just built up some of these shields - D1 works on Pin16 but i can not get D2 to work. In WLED i tried Pin1 and Pin3, but anyway Pin1 is always red and not selectable (v13.3 with Dallas / Display usermod). I tried to solder the bridge on the pcb to IO1 and IO3 - but i never get any working signal on D2/CLK.

Whats wrong ?

**Comment by srg74** [comment]
If gpio1 is always red that means you have set that pin somewhere else in settings.

**Comment by DarthWeber** [comment]
Sorry, got it to work. Only Pin3 is abailable - Pin1 ist blocked by anything else. I am quite sure that this was different in previous versions but maybe i am wrong.

May problem behind this was a curcuit on the solder bridge due to the change from io1 to io3

Maybe it would be senseful to mention this limitation an the layout / and or doc ?

**Comment by DarthWeber** [comment]
> If gpio1 is always red that means you have set that pin somewhere else in settings.

Thats what i also thought - but it isn't defined anywhere - i checked all buttons,relay,dallas,display,....

**Comment by srg74** [comment]
I will check firmware. Let’s see what happens.

**Comment by DarthWeber** [comment]
Great. Pls check the one with Esp32 Dallas display. Display is disabled. -------- Originalnachricht --------Betreff: Re: [srg74/WLED-wemos-shield] D2 not working (Issue #77)Von: srg74 An: srg74/WLED-wemos-shield Cc: DarthWeber ,Author 

I will check firmware. Let’s see what happens.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/srg74/WLED-wemos-shield/issues/77#issuecomment-1293440227",

"url": "https://github.com/srg74/WLED-wemos-shield/issues/77#issuecomment-1293440227",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by DarthWeber** [comment]
i am confused. It is working perfect if i solder the bridge to IO1/TX but must select Pin3 in WLED. Semms like pin1 and 3 are swapped somewhere in the firmware....

**Comment by srg74** [comment]
Some of the the esp32 boards manufacturers swapping pins. So most likely it’s a hardware.
