### ISSUE TITLE
V14 ESP02 bin

### ISSUE THREAD

**Issue by Ankonian1** [srg74/WLED-wemos-shield#78]
Apologies, I am not seeing an ESP02 build for V14. I am using an Anthom LS-4P with Govee WS2814A strips. Need the SK6812 swap feature.

**Comment by srg74** [comment]
https://github.com/srg74/WLED-wemos-shield/blob/master/resources/Firmware/WLED_wemos_shield/v0.14.0-b0/WLED_0.14.0-b0_SP501E_2m.bin

**Comment by Ankonian1** [comment]
Thank you. That OTA was unsuccessful though :(
