### ISSUE TITLE
[sp511e] update/downgrade fail with webinterface

### ISSUE THREAD

**Issue by schwatter** [srg74/WLED-wemos-shield#91]
Hello,

i have five SP511E.
Hardwire and flash always works. But update or downgrade not.
I get always in the webinterface:
Update failed!
Please check your file and retry!

Tested with WLED_0.13.3_SP511E_2m.bin and WLED_0.14.0-b0_SP511E_2m.bin

Any hint?

regards schwatter

**Comment by srg74** [comment]
Will be investigated. But as code grows it might happen that 2M memory is not sufficient for OTA.
