### ISSUE TITLE
Gerber Files

### ISSUE THREAD

**Issue by dakky** [srg74/WLED-wemos-shield#93]
Hello

do you share the gerber files? The supplier you offer does ship to europe for horrendous fees only.

greetings
Dakky

**Comment by dakky** [comment]
I didn't see that you can select other delivery service provider. 6$ for deilvery within 15 business days is fair

**Comment by srg74** [comment]
Actually all questions regarding shipping you have to ask from PCBway. I'm not involved in their process, just I shared my project.
