### ISSUE TITLE
Digi-Key reports that 1N4148-P-TAP is obsolete

### ISSUE THREAD

**Issue by seganku** [srg74/WLED-wemos-shield#97]
They still stock this part, but it might be prudent to spec a non-obsolete equivalent.

BOM entry:
D1 | 1N4148 | Vishay Diodes | 1N4148-P-TAPGICT-ND | 1N4148-P-TAP | 1

Looking forward to putting this together, but my shipment from Digi-Key has been stuck in Fargo, ND since 2022-12-21.  Ha!

**Comment by srg74** [comment]
It always will be a situation like this but similar products is available for example 1N4148FS-ND
Also now fully assembled board is available here https://www.tindie.com/products/22307/

**Comment by Jack187** [comment]
Will a 1N4150TR (C5342941, LCSC.com) also be fine? Package is eqeivalent and looks similar from spec.
Thanks in advance

**Comment by srg74** [comment]
Look like can be a substitute.
