### ISSUE TITLE
Pinout for VXO7805-1000 is not the same as VXO7805-500

### ISSUE THREAD

**Issue by seganku** [srg74/WLED-wemos-shield#98]
https://github.com/srg74/WLED-wemos-shield/wiki/Options says:
"⚠️ IMPORTANT: If you connect Additional devices to shield, 5V buck converter PS1 must be replaced with more powerful. VXO7805-1000 (Digikey p/n: 102-4258-ND) ⚠️"

The pinout for the VXO7805-1000 ([datasheet](https://www.cui.com/product/resource/vxo78-1000.pdf)) is reversed from that of the VXO7805-500 ([datasheet](https://www.cui.com/product/resource/vxo78-500.pdf)).  The board design does not have space for the VXO7805-1000, unless the pins are moved to the other side of the component (which proved annoyingly resilient to solder wick).

**Comment by srg74** [comment]
You absolutely correct.
