### ISSUE TITLE
Flashing when switching on the relais

### ISSUE THREAD

**Issue by 0711christian** [srg74/WLED-wemos-shield#99]
I´ve build the  V3 shield three times now and have some problems with white flashes on the first LEDs when switching on the relais on all of them.

I´m running an ESP32 and the problem only happens when I´m powering more than about 100 LEDs.
I´ve already tested it with WS2812B and SK6812 and also run v0.13.3 and v0.14.0-b1 but it stays the same. One single flash on the first 1-4ish LEDs before switching to the normal effect.

**Comment by srg74** [comment]
Such an issue never have been reported before. Users have been running more than 100 LEDs and everything was ok. For more detailed review please visit WLED Discord channel https://discord.gg/KuqP7NE
